'use client'
import { useState } from "react"
import { poppins } from "./ui/fonts"
import Image from "next/image"

export default function FAQs() {
    const [isvisible, setisvisible] = useState(0);
    function visibility(i: number) {
        setisvisible(i);
    }
    return (
        <>
            <div className="w-full p-10 justify-center">
                <h1 className={`text-[#123458] ${poppins.className} font-bold text-4xl w-full flex justify-center`}>FAQs</h1>
                <h1 className={`text-[#123458] ${poppins.className}  text-xl w-full flex justify-center align-middle`}>Questions and Answers</h1>
                <div className="flex justify-center w-full mt-10">
                    <div className="w-full md:w-[70%] grid grid-cols-1">
                        <div className="flex  bg-white h-auto p-2 border-1 border-gray-200 ">
                            How much does it cost to use the platform? <div className="m-1 ml-auto" onClick={() => { visibility(1) }}><Image src={"/down-arrow.png"} alt="down" height={40} width={20} /></div>
                        </div>
                        <div className={`text-gray-500 bg-white h-auto p-2 border-1 border-gray-200 ${isvisible === 1 ? "block" : "hidden"}`} >
                            Our platform is completely free to use.
                        </div>

                        <div className="flex  bg-white h-auto p-2 border-1 border-gray-200 ">
                            How does the platform create my resume and portfolio? <div className="m-1 ml-auto" onClick={() => { visibility(2) }}><Image src={"/down-arrow.png"} alt="down" height={40} width={20} /></div>
                        </div>
                        <div className={`text-gray-500 bg-white h-auto p-2 border-1 border-gray-200 ${isvisible === 2 ? "block" : "hidden"}`} >
                            Our platform uses the information you provide to automatically generate a professional resume and portfolio. Simply enter your details, and our system does the rest, ensuring your documents are polished and ready to share.
                        </div>

                        <div className="flex  bg-white h-auto p-2 border-1 border-gray-200 ">
                            How can I share my resume or portfolio? <div className="m-1 ml-auto" onClick={() => { visibility(3) }}><Image src={"/down-arrow.png"} alt="down" height={40} width={20} /></div>
                        </div>
                        <div className={`text-gray-500 bg-white h-auto p-2 border-1 border-gray-200 ${isvisible === 3 ? "block" : "hidden"}`} >
                            You can share your resume or portfolio using the live link generated by our platform. Additionally, you have the option to download your resume as a PDF for offline sharing.
                        </div>

                        <div className="flex  bg-white h-auto p-2 border-1 border-gray-200 ">
                            Do you offer customer support? <div className="m-1 ml-auto" onClick={() => { visibility(4) }}><Image src={"/down-arrow.png"} alt="down" height={40} width={20} /></div>
                        </div>
                        <div className={`text-gray-500 bg-white h-auto p-2 border-1 border-gray-200 ${isvisible === 4 ? "block" : "hidden"}`} >
                            Yes, You can reach out to us using the contact details provided in the Contact Us section. 
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}